# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  name: glueops/tacos_app_react_js
  tag: v0.2.2
containerPort: 3000
containerName: app
cpuLimitInM: null # defaults to 110% of cpuRequestInM
cpuRequestInM: 300
memoryLimitInMi: null # defaults to 110% of memoryRequestInMi
memoryRequestInMi: 32
#<name>.apps.<cluster-environment-name>.<companykey>.glueopshosted.rocks
captain_domain: <cluster-environment-name>.<companykey>.glueopshosted.com
domain: nil
vault_path: nil
vault_path_overrides: nil
vault_path_registry_credentials: nil

prometheus-alertmanagerconfig:
  # -- These labels are additional filters you can use to keep these notifications for one particular team, component, or alert. Note: you must set the same filters (with the exception of alertname) on the alert definition itself. The alert definition is also refered to as the prometheusrule.
  labels:
    team: nil
    component: nil
    alertname: nil

  # -- Amount of time to fire an alert again after the first one is sent.
  route:
    repeatInterval: "5m"
    groupInterval: "5m"
