# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  name: glueops/tacos_app_react_js
  tag: v0.2.2
containerPort: 3000
#<name>.apps.<cluster-environment-name>.<companykey>.glueopshosted.rocks
domain: nil 
vault_path: nil
vault_path_overrides: nil


