# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appName: antoniostacos-home-page
image: glueops/tacos_app_react_js:v0.2.2
containerPort: 3000
domain: <your-domain-goes-here>

