podDisruptionBudget:
  enabled: true
deployment:
  enabled: true
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
  livenessProbe:
    httpGet:
      path: /healthz_nodownstream
      port: 9999
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
serviceAccount:
  create: true
  name: new-service-account
  labels:
    key: value
  annotations:
    serviceaccount.annotations.example.com/foo: bar
