image:
  registry: ghcr.io
  repository: "stefanprodan/podinfo"
  tag: "6.3.6"
  port: 9898
deployment:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 50m
      memory: 50Mi
  livenessProbe:
    httpGet:
      path: /healthz
      port: 9898
  readinessProbe:
    httpGet:
      path: /healthz
      port: 9898
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - "example-app"
          topologyKey: topology.kubernetes.io/zone