apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-cpu-exceeds-requested
spec:
  groups:
  - name: {{ .Release.Name }}-cpu-exceeds-requested
    rules:
    - alert: {{ .Release.Name }}-cpu-exceeds-requested
      expr: |
        sum(
          rate(container_cpu_usage_seconds_total{container!="", container!="POD", namespace="{{ .Release.Namespace }}", container=~"{{ .Release.Name }}"}[5m])
        ) by (pod, namespace, container)
        / on (pod, namespace, container) group_left
        sum(kube_pod_container_resource_requests{resource="cpu", namespace="{{ .Release.Namespace }}", container=~"{{ .Release.Name }}"}) by (pod, namespace, container) > 1
      for: 1m
      annotations:
        description: {{ .Release.Name }} has exceeded requested CPU.
      labels:
        {{- if ne (toString (index .Values "alerts" "labels" "team")) "nil" }}
        team: {{ index .Values "alerts" "labels" "team" | nindent 8 }}
        {{- end }}
        {{- if ne (toString (index .Values "alerts" "labels" "component")) "nil" }}
        component: {{ index .Values "alerts" "labels" "component" | nindent 8 }}
        {{- end }}
        alertname: {{ .Release.Name }}-cpu-exceeds-requested
        namespace: {{ .Release.Namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-memory-exceeds-requested
spec:
  groups:
  - name: {{ .Release.Name }}-memory-exceeds-requested
    rules:
    - alert: {{ .Release.Name }}-memory-exceeds-requested
      expr: |
        sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}", container!="", container!="POD"}) by (pod, namespace, container)
        / on (pod, namespace, container) group_left
        sum(kube_pod_container_resource_requests{resource="memory", namespace="{{ .Release.Namespace }}"}) by (pod, namespace, container) > 1
      for: 1m
      annotations:
        description: {{ .Release.Name }} has exceeded requested memory.
      labels:
        {{- if ne (toString (index .Values "alerts" "labels" "team")) "nil" }}
        team: {{ index .Values "alerts" "labels" "team" | nindent 8 }}
        {{- end }}
        {{- if ne (toString (index .Values "alerts" "labels" "component")) "nil" }}
        component: {{ index .Values "alerts" "labels" "component" | nindent 8 }}
        {{- end }}
        alertname: {{ .Release.Name }}-memory-exceeds-requested
        namespace: {{ .Release.Namespace }}

