apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
        env: 
        - name: GLUEOPS_PREVIEW_DOMAIN
          value: {{ .Release.Name }}.apps.{{ .Values.captain_domain }}
        {{- if ne .Values.vault_path "nil" }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}
        {{- if ne .Values.vault_path_overrides "nil" }}
        - secretRef:
            name: {{ .Release.Name }}-overrides
            optional: true
        {{- end }}
        {{- end }}
        resources:
          requests:
            {{- if .Values.cpuRequestInM }}
            cpu: {{ .Values.cpuRequestInM }}m
            {{- end }}
            {{- if .Values.memoryRequestInMi }}
            memory: {{ .Values.memoryRequestInMi }}Mi
            {{- end }}
          limits:
            {{- if .Values.cpuLimitInM }}
            cpu: {{ .Values.cpuLimitInM }}m
            {{- else if .Values.cpuRequestInM }}
            cpu: {{ mulf .Values.cpuRequestInM 1.1 }}m
            {{- else }}
            {{- end }}
            {{- if .Values.memoryLimitInMi }}
            memory: {{ .Values.memoryLimitInMi }}Mi
            {{- else if .Values.memoryRequestInMi }}
            memory: {{ mulf .Values.memoryRequestInMi 1.1 }}Mi
            {{- else }}
            {{- end }}
      {{- if ne .Values.vault_path_registry_credentials "nil" }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-reg-cred
      {{- end }}
