apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
        env: 
        - name: GLUEOPS_PREVIEW_DOMAIN
          value: {{ .Release.Name }}.apps.test-11-np.venkata.glueopshosted.rocks
        {{- if ne .Values.vault_path "nil" }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}
        {{- end }}


          
