apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
        env: 
        - name: GLUEOPS_PREVIEW_DOMAIN
          value: {{ .Release.Name }}.apps.{{ .Values.captain_domain }}
        {{- if ne .Values.vault_path "nil" }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}
        {{- if ne .Values.vault_path_overrides "nil" }}
        - secretRef:
            name: {{ .Release.Name }}-overrides
            optional: true
        {{- end }}
        {{- end }}
        resources:
          requests:
            {{- if ne .Values.cpuRequest "nil" }}
            cpu: {{ .Values.cpuRequest }}m
            {{- end }}
            {{- if ne .Values.memoryRequest "nil" }}
            memory: {{ .Values.memoryRequest }}Mi
            {{- end }}
          limits:
            {{- if ne .Values.cpuLimit "nil" }}
            cpu: {{ .Values.cpuLimit }}m
            {{- else if ne .Values.cpuRequest "nil" }}
            cpu: {{ mul .Values.cpuRequest 1.1 }}m
            {{- else }}
            {{- end }}
            {{- if ne .Values.memoryLimit "nil" }}
            memory: {{ .Values.memoryLimit }}Mi
            {{- else if ne .Values.memoryRequest "nil" }}
            memory: {{ mul .Values.memoryRequest 1.1 }}Mi
            {{- else }}
            {{- end }}
      {{- if ne .Values.vault_path_registry_credentials "nil" }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-reg-cred
      {{- end }}
