{{- if .Values.externalSecret.enabled  }}
{{- range $nameSuffix, $data := .Values.externalSecret.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.name" $ }}-{{ $nameSuffix }}
  namespace: {{ include "app.namespace" $ }}
  labels:
    {{- include "chart.commonLabels" $ | indent 4 }}
  annotations:
    {{- include "chart.commonAnnotations" $ | indent 4 }}
spec:
  refreshInterval: {{ $data.refreshInterval | default $.Values.externalSecret.refreshInterval }}
  {{- if and (not $data.data) (not $data.dataFrom) }}
  {{- fail "Data or datafrom not specified for secret {{ include 'app.name' $ }}-{{ $nameSuffix }} " }}
  {{- end }}

  {{- if $data.data }}
  data:
  {{- range $secretKey, $remoteRef := $data.data}}
    - secretKey: {{ $secretKey }}
    {{- toYaml $remoteRef | nindent 6 }}
  {{- end }}
  {{- end }}
  
  {{- if $data.dataFrom }}
  dataFrom:
  - extract: {{ toYaml $data.dataFrom | nindent 6  }}
  {{- end }}

  {{- if $data.secretStore }}
  secretStoreRef:
    name: {{ $data.secretStore.name }}
    kind: {{ $data.secretStore.kind | default "ClusterSecretStore" }}
  {{- else }}
  secretStoreRef:
    name: {{ $.Values.externalSecret.secretStore.name }}
    kind: {{ $.Values.externalSecret.secretStore.kind | default "ClusterSecretStore" }}
  {{- end }}
  target:
    name: {{ $data.name | default (printf "%s-%s" (include "app.name" $) $nameSuffix) }}
    template:
      type: {{ $data.type | default "Opaque" }}
      {{- if or $data.annotations $data.labels}}
      metadata:
        {{- if $data.annotations }}
        annotations: {{ toYaml $data.annotations | nindent 10 }}
        {{- end }}
        {{- if $data.labels }}
        labels: {{ toYaml $data.labels | nindent 10 }}
        {{- end }}
      {{- end }}

{{- end}}
{{- end}}