{{- if ne .Values.vault_path "nil" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  dataFrom: 
  - find: 
      name:
        regexp: "{{ .Values.vault_path }} | {{ .Values.vault_path_overrides }}"
{{- end}}
# {{- if ne .Values.vault_path_overrides "nil" }}
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{ .Release.Name }}-overrides
# spec:
#   refreshInterval: "15s"
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: {{ .Release.Name }}-overrides
#   dataFrom: 
#   - extract: 
#       key: {{ .Values.vault_path_overrides }}
# {{- end}}
