{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.entries }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" $ }}-{{.name}}
  namespace: {{ include "app.namespace" $ }}
  labels:
    {{- include "chart.commonLabels" $ | indent 4 }}
    {{- if $.Values.ingress.labels }}
    {{- range $key, $value := $.Values.ingress.labels }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- if .labels }}
    {{- range $key, $value := .labels }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
  annotations:
    {{- include "chart.commonAnnotations" $ | indent 4 }}
    {{- if $.Values.ingress.annotations }}
    {{- range $key, $value := $.Values.ingress.annotations }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- if .annotations }}
    {{- range $key, $value := .annotations }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end }}
  rules:
  {{- if .hosts }}
  {{- range .hosts }}
  - host: {{.hostname}}
    http:
      paths:
      {{- if .paths }}
      {{- range .paths }}
      - path: {{ .path | default "/" }}
        pathType: {{ .pathType | default "ImplementationSpecific" }}
        backend:
          service:
            name: {{ .serviceName | default (include "app.name" $)}}
            port: 
              {{- if .servicePortName }}
              name: {{.servicePortName | default "http" }}
              {{- else }}
              number: {{ int (.servicePortNumber | default (include "app.port" $)) }}
              {{- end }}
      {{- end }}
      {{- else }}
      - path: "/"
        pathType: "ImplementationSpecific"
        backend:
          service:
            name: {{ include "app.name" $}}
            port: 
              number: {{ int (include "app.port" $) }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- tpl (toYaml .tls) $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
