apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: glueops-cert-zerossl-prod
spec:
  ingressClassName: external-ingress-nginx
  # hosts:
  #   - host: test-app.gcp.glueops.rocks
  rules:
  - host: {{ .Release.Name }}.apps.test-10-np.venkata.glueopshosted.rocks
    http:
      paths:
        - backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.containerPort }}
          path: /
          pathType: Prefix
{{- if ne .Values.domain "nil" }}
  - host: {{ .Values.domain }}
    http:
      paths:
        - backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.containerPort }}
          path: /
          pathType: Prefix
{{- end}}
  tls:
    - secretName: {{ .Release.Name }}-tls
      hosts:
        - {{ .Release.Name }}.apps.test-10-np.venkata.glueopshosted.rocks
{{- if ne .Values.domain "nil" }}
    - secretName: {{ .Release.Name }}-tls-customer-domain
      hosts:
        - {{ .Values.domain }}
{{- end}}
