apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: public
  # hosts:
  #   - host: test-app.gcp.glueops.rocks
  rules:
  - host: *.apps.first-gcp.bart.onglueops.rocks
    http:
      paths:
        - backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.containerPort }}
          path: /(.*)
          pathType: Prefix
{{- if ne .Values.domain "nil" }}
  - host: {{ .Values.domain }}
    http:
      paths:
        - backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.containerPort }}
          path: /
          pathType: Prefix
{{- end}}
{{- if ne .Values.domain "nil" }}
  tls:
    - secretName: {{ .Release.Name }}-tls-customer-domain
      hosts:
        - {{ .Values.domain }}
{{- end}}
