{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  namespace: {{ template "app.namespace" . }}
  labels:
    {{- include "chart.commonLabels" . | indent 4 }}
    {{- if .Values.serviceAccount.labels }}
    {{- range $key, $value := .Values.serviceAccount.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  annotations:
    {{- include "chart.commonAnnotations" . | indent 4 }}
    {{- if .Values.serviceAccount.annotations }}
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
# ---
# apiVersion: v1
# kind: Secret
# type: kubernetes.io/service-account-token
# metadata:
#   name: "{{ include "chart.serviceAccountName" . }}-token"
#   labels:
#     {{- include "chart.commonLabels" . | indent 4 }}
#   annotations:
#     kubernetes.io/service-account.name: {{ include "chart.serviceAccountName" . }}
#     {{- include "chart.commonAnnotations" . | indent 4 }}
{{- end -}}
