apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    name: https