{{- if and .Values.statefulSet.enabled (not .Values.deployment.enabled) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "chart.commonLabels" . | indent 4 }}
  annotations:
    {{- include "chart.commonAnnotations" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.appLabels" . | indent 6 }}
      {{- if .Values.statefulSet.matchLabels }}
      {{- toYaml .Values.statefulSet.matchLabels | nindent 6 }}
      {{- end }}
  serviceName: {{ .Values.statefulSet.serviceName | default (include "app.name" .) }}
  {{- if .Values.statefulSet.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.statefulSet.revisionHistoryLimit }}
  {{- end }}
  replicas: {{ int (.Values.statefulSet.replicas | default 1) }}
  {{- if .Values.statefulSet.minReadySeconds }}
  minReadySeconds: {{ .Values.statefulSet.minReadySeconds }}
  {{- end }}
  {{- if .Values.statefulSet.updateStrategy }}
  updateStrategy:
    {{- $strategy := .Values.statefulSet.updateStrategy |  default "RollingUpdate" }}
    type: {{ $strategy }}
  {{- end }}

  {{- $context :=  merge .Values.statefulSet (dict "resourceType" "statefulSet" "Chart" $.Chart "Root" $) }}
  template: 
  {{- include "chart.podTemplate" $context | nindent 4 }}
  # volumeClaimTemplates
  {{- if .Values.statefulSet.volumeClaimTemplates }}
  {{- range $key, $value := .Values.statefulSet.volumeClaimTemplates }}
  volumeClaimTemplates:
  - metadata:
      name: {{$key}}
    spec:
      accessModes: 
        - {{$value.accessModes}}
      {{- if hasKey $value "storageClassName" }}
      storageClassName: {{$value.storageClassName}}
      {{- end }}
      resources:
        requests:
          storage: {{$value.requestsStorage}}
  {{- end }}
  {{- end }}

{{- end }}