name: test
on: [push]

jobs:
  k8s-test:
    runs-on: ubuntu-22.04
    steps:
      # GitHub Action reference: https://github.com/jupyterhub/action-k3s-helm
      - name: Kubernetes
        uses: jupyterhub/action-k3s-helm@v3
        with:
          # See available:
          # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
          # - k3s versions at https://github.com/k3s-io/k3s/tags
          # - helm versions at https://github.com/helm/helm/tags
          k3s-version: v1.26.3+k3s1
          helm-version: v3.7.0
          metrics-enabled: false
          traefik-enabled: false

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Install
        env:
          KUBE_LINTER_VER: 0.6.3
          KUBE_SCORE_VER: 1.16.1
          POLARIS_VER: 7.4.2
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq yamllint wget
          cd /tmp
          wget -q https://github.com/stackrox/kube-linter/releases/download/v${KUBE_LINTER_VER}/kube-linter-linux && sudo mv kube-linter-linux /usr/local/bin/kube-linter && sudo chmod +x /usr/local/bin/kube-linter
          wget -q https://github.com/zegl/kube-score/releases/download/v${KUBE_SCORE_VER}/kube-score_${KUBE_SCORE_VER}_linux_amd64 && sudo mv kube-score_${KUBE_SCORE_VER}_linux_amd64 /usr/local/bin/kube-score && sudo chmod +x /usr/local/bin/kube-score
          wget -q https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz && tar xf kubeval-linux-amd64.tar.gz && sudo mv kubeval /usr/local/bin && sudo chmod +x /usr/local/bin/kubeval
          wget -q https://github.com/FairwindsOps/polaris/releases/download/${POLARIS_VER}/polaris_linux_amd64.tar.gz && tar xf polaris_linux_amd64.tar.gz && sudo mv polaris /usr/local/bin && sudo chmod +x /usr/local/bin/polaris
        
      - name: Verify
        run: |
          yamllint --version
          kubeval --version
          kube-linter version
          kube-score version
          polaris version
          
      - name: Helm install
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl version
          kubectl get nodes
          kubectl get pods --all-namespaces
          helm version
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install external-secrets external-secrets/external-secrets --version 0.8.3 --wait
          helm install keda kedacore/keda --version 2.10.2 --wait
          helm install prometheus prometheus-community/prometheus-operator-crds --wait
          helm list
          kubectl get pod
          

      - name: Checks
        run: |
          make lint
          make unittest
          make test

